---
# This playbook will create a Digital Ocean droplet

- hosts: localhost

  vars:
    do_api_token: 12b6186f3674cf7992dfbd91718b845d810abd5161500dbcbecd3ae588a20ac3
    droplet_name: test-droplet
    droplet_size: 512mb
    droplet_region: nyc2
    droplet_image: ubuntu-14-04-x64
    droplet_ssh_key_ids: 759949,1652083 # no spaces between entries; only commas

  tasks:
  
  - name: create new droplet
    digital_ocean:
      state: present
      ssh_key_ids: "{{ droplet_ssh_key_ids }}"
      command: droplet
      name: "{{ droplet_name }}"
      api_token: "{{ do_api_token }}"
      size_id: "{{ droplet_size }}"
      region_id: "{{ droplet_region }}"
      image_id: "{{ droplet_image }}"
      wait_timeout: 600
      
    register: create_results
    
  - debug: msg="ID is {{ create_results.droplet.id }}"
  - debug: msg="IP is {{ create_results.droplet.ip_address }}"
    